//admin api

@url = http://localhost:8000/api/v1

//create new admin user
POST {{url}}/admin/register
Content-Type: application/json

//Now copy the data from console log from registration page
{"address": "1 george st Sydney",

"email"
: 
"Shital@gmail.com",
"fName"
: 
"Shital",
"lName"
: 
"Rayamajhi",
"password"
: 
"Live@123",
"phone": "12343456"}

# login user
POST {{url}}/admin/login
Content-Type: application/json
{
    "email":"Shital@gmail.com",
    "password":"Sr@1234"
}

//category mgmt api
POST {{url}}/categories
Content-Type: application/json

{
    "name":"Computer"
}